// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3EdlxNtrsNqAdAVlEHYrZkR2hcG_vNUo',
    appId: '1:648015300968:web:5bd6ea77f3356935636edd',
    messagingSenderId: '648015300968',
    projectId: 'power-hive-94c09',
    authDomain: 'power-hive-94c09.firebaseapp.com',
    databaseURL: 'https://power-hive-94c09-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'power-hive-94c09.firebasestorage.app',
    measurementId: 'G-C5JF1TT6TJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM3j7Z5dWy2qpURXPmAQPwnGooa52Rdfw',
    appId: '1:648015300968:android:f8c5183f81fc5c35636edd',
    messagingSenderId: '648015300968',
    projectId: 'power-hive-94c09',
    databaseURL: 'https://power-hive-94c09-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'power-hive-94c09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeiZvyzmHDStvxBayQuvvERQpehh0Qbq8',
    appId: '1:648015300968:ios:7fe6af26d37e43d6636edd',
    messagingSenderId: '648015300968',
    projectId: 'power-hive-94c09',
    databaseURL: 'https://power-hive-94c09-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'power-hive-94c09.firebasestorage.app',
    iosBundleId: 'com.example.powerHive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeiZvyzmHDStvxBayQuvvERQpehh0Qbq8',
    appId: '1:648015300968:ios:7fe6af26d37e43d6636edd',
    messagingSenderId: '648015300968',
    projectId: 'power-hive-94c09',
    databaseURL: 'https://power-hive-94c09-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'power-hive-94c09.firebasestorage.app',
    iosBundleId: 'com.example.powerHive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3EdlxNtrsNqAdAVlEHYrZkR2hcG_vNUo',
    appId: '1:648015300968:web:a9867a5ab1eeaab5636edd',
    messagingSenderId: '648015300968',
    projectId: 'power-hive-94c09',
    authDomain: 'power-hive-94c09.firebaseapp.com',
    databaseURL: 'https://power-hive-94c09-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'power-hive-94c09.firebasestorage.app',
    measurementId: 'G-F53QFDV9E0',
  );
}
